Test run of pipeline to test functionality and provide code feedback.
ClinicalGenomicsGBG/hbv_nano pull request #1
Opened 2024-06-29 14:08 UTC by daniel-e-schmidt

## Contents
Review deadline:
2024-07-29

Main reviewers: @SannaAb, @pauladisanto and @JPWerling 

### The What
1. Test run the pipeline.
2. Provide feedback on code.

### The Why
1. Verify that the pipeline runs as expected and that the instructions for running it are clear.
2. Find potential issues in the code and give suggestions on areas where it can be approved. These may include things such as functionality, unclear code etc..

### The How
Instructions for running the pipeline are provided on Confluence.

### This [update](https://semver.org/) is:
- [X ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Test Procedure
See Confluence.

### Installation and initiation
See Confluence.

### Tests
Run the pipeline and check the output in folder output/clinic and that it contains:
1. Consensus .fasta files.
2. variant_calling.txt files.
3. A qc_clinic.csv file.

### Expected outcome
That the pipeline runs smoothly and that an email containing exit status = 0 is received.
Check that the files in output/clinic exist and are not empty. For the variant_calling files drug resistance mutations should be found in the end of at least one file.

## Verifications
- [ ] Code reviewed by @SannaAb 
- [ ] Code reviewed by @pauladisanto
- [ ] Code reviewed by @JPWerling

2024-08-14 13:21 UTC, CEJ-R commented
Pipeline worked. Left some comments/feedback on your confluence how-to. Will look at the code next; but the pipeline worked!

2024-08-15 07:08 UTC, CEJ-R requested changes
As it stands I'd say the python parts need a bit of work. I'm not sure how they'd behave in a snakemake setting with my proposed changes, but as python code goes they're quite hard to read. Lift out functions, add docstrings, and move away from handing dataframes. If not here, then in future.

2024-08-15 07:08 UTC, CEJ-R commented on workflow/scripts/vcf_modification.py
This is a bit of work. 
- First Id say, you need to break this down into smaller functions. As it stands it's very hard to follow the logic.
- Secondly, as in `qc.py` you'd benefit greatly from one separate "Read file" function, returning a dict. This way you'd not have to add so much logic to handing the dataframes. Simply ask the specific dict for that info and you're done.
- Thirdly, don't nest your loops so much. That can very easily lead to a lot of problems. If you must cycle more than twice, do so once, return the data into a var, and cycle that var separately. That way you can add checks inbetween, reducing the issue and raising readability.
- Fourth(ly?): Move the tables of amino acids, positions, drugs, etc. (all constants) to a config. When these need changing you'd do it there, not fiddle around in the code, which can (and will) break more easily from that.

2024-08-15 07:08 UTC, CEJ-R commented on workflow/scripts/wrapper.py
> +if not sample_sheet['type'].str.contains('neg', na=False).any():
As above, what if the user specifies this in caps? One way of doing this simple is to use .lower to force both temporarily to be lower case.

2024-08-15 07:08 UTC, CEJ-R commented on workflow/scripts/wrapper.py
> +with open('config/wrapper_config.yaml', 'r') as f:
Id' also put all of the below into a function to better handle any weird business that might arise.

2024-08-15 09:57 UTC, daniel-e-schmidt commented on README.md
> +.../hbv_nano
Absolutely!

2024-08-19 08:12 UTC, JPWerling commented on workflow/scripts/qc.py
> +df_clinic.to_csv(f'{output}/clinic/qc.csv', index=False)
@CEJ-R That it should or should not exist?

2024-08-20 08:43 UTC, CEJ-R commented on workflow/scripts/qc.py
> +df_clinic.to_csv(f'{output}/clinic/qc.csv', index=False)
@JPWerling Always exist! We're not code-savages, are we?

2024-08-26 13:47 UTC, CEJ-R reviewed
Where you've improved it's much better. Good work there! As expected the places where you've not touched yet still needs some work. As for the new comments, there are just some small stuff.
Overall: Much better!

2024-08-26 13:47 UTC, CEJ-R commented on README.md
> +./build_images.sh
Might be good to put this as `bash ./build_images.sh` to avoid confusion/issues with shebang/permissions.

2024-08-26 13:47 UTC, CEJ-R commented on README.md
> +The pipeline takes gzipped `.fastq.gz` files in the format `{sample_01}.fastq.gz`, `{sample_02}.fastq.gz`, ...,  `{sample_**}.fastq.gz` as input.
Nitpick: Last could be put as `{sample_n}.fastq.gz` to make it more general.

2024-08-26 13:47 UTC, CEJ-R commented on README.md
Much clearer this time around!

2024-08-26 13:47 UTC, CEJ-R commented on workflow/scripts/copy_files.py
> +    try:
Hmm... I'm wondering if this should be moved to the if __name__ thing. There you could add the if-statement and also feed the function with the input. As it now stands I instinctively looked for `copy_files():` input.

2024-08-26 13:47 UTC, CEJ-R commented on workflow/scripts/error_rate.py
> +    try:
Again maybe move this down. I think that would make me as a reader more easily see what makes the function work.

2024-08-26 13:47 UTC, CEJ-R commented on workflow/scripts/qc.py
> +    '''Perform QC checks'''
Might want some more info here. QC of what? On what?

2024-08-26 13:47 UTC, CEJ-R commented on workflow/scripts/wrapper.py
> +def concatenate(sample_sheet, inpath, outpath):
This would be good if you add some comments in the code. E.g. what the smaller steps do.

2024-08-27 07:37 UTC, JPWerling requested changes
Few points i think could be improved.

I made some changes of my own in the git branch `golden` where I try and implement some stricter versioning of dependencies. You could look there and implement the changes yourself here or leave the branch as is, but the versions need to be set more specifically for both python env and singu images

2024-08-27 07:37 UTC, JPWerling commented on workflow/Snakefile
> +        config["fastp"]
You mentioned snakemake8 bringing some special functionality running singularities. This looks very standard?

2024-08-27 07:37 UTC, JPWerling commented on workflow/scripts/copy_files.py
> +    output = config['output']
When is `snakemake.params.output` supposed to be filled? Will this not succeed with an empty string for the param?

2024-08-27 07:37 UTC, JPWerling commented on workflow/scripts/copy_files.py
> +    df = pd.read_csv(f'{output}/samtools/minimum_error_rates.csv')
Consider less "bloated", more vanilla way of parsing csv:
```
import csv
with open('names.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        print(row['first_name'], row['last_name'])
```

2024-08-27 07:37 UTC, JPWerling commented on workflow/scripts/copy_files.py
> +                    out_fa.write(f'>{read_id}.{ref}\n')
`print(f'>{read_id}.{ref}', file=out_fa)` is an alternative if you dont want to add newlines all the time.

2024-08-27 07:37 UTC, JPWerling commented on workflow/scripts/environment.yaml
> +  - pandas
```
name: hbv_nano
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - snakemake-minimal=8.18.0
  - pip=24.2
  - pip:
    - biopython==1.84
    - pandas==2.2.2
```

2024-08-27 07:37 UTC, JPWerling commented on workflow/scripts/error_rate.py
> +df = df.loc[df.groupby("read_id")["error_rate"].idxmin()].reset_index(drop=True)   # get the sample with the lowest error rate for each read_id
This is impossible to understand for anyone not well-read on all things pandas

2024-11-12 19:50 UTC, closed without merging